"""
dashboard.py — Builds live_data.js from the latest report JSON.

All AI content is pre-generated by summarizer.py and stored in the report.
This just reads it and writes live_data.js for the frontend.
"""

import json
import os
from datetime import datetime, timezone
from pathlib import Path

REPORTS_DIR = Path("reports")


def _level_to_pct(level: str) -> int:
    return {"LOW": 30, "MEDIUM": 52, "HIGH": 75, "CRITICAL": 92}.get(level, 50)


def _level_color(level: str) -> str:
    return {"LOW":"var(--green)","MEDIUM":"var(--amber)","HIGH":"#c87830","CRITICAL":"var(--red)"}.get(level, "var(--text3)")


def _actor_class(actor: str) -> str:
    return {"US":"p-blue","Israel":"p-blue","Iran":"p-red","Hamas":"p-red","Hezbollah":"p-red"}.get(actor, "p-gray")


def _sig_badge(sig: str) -> str:
    return {"HIGH":"b-crit","MEDIUM":"b-high","LOW":"b-gray"}.get(sig, "b-gray")


def _time_ago(ts: str) -> str:
    try:
        dt = datetime.strptime(ts, "%Y-%m-%d %H:%M UTC").replace(tzinfo=timezone.utc)
        diff = int((datetime.now(timezone.utc) - dt).total_seconds())
        if diff < 60:    return "just now"
        if diff < 3600:  return f"{diff // 60} min ago"
        if diff < 86400:
            h = diff // 3600
            return f"{h} hr{'s' if h>1 else ''} ago"
        d = diff // 86400
        return f"{d} day{'s' if d>1 else ''} ago"
    except Exception:
        return ts


def _normalise_type(raw_type: str) -> str:
    """
    Normalise the type field from AI output to one of the
    6 categories the index.html Daily Digest expects.
    """
    t = (raw_type or "war").lower().replace(" ", "_").replace("-", "_")
    # Map common AI output variations to our categories
    mapping = {
        "war":          "war",
        "military":     "military",
        "diplomacy":    "diplomacy",
        "diplomatic":   "diplomacy",
        "wider_war":    "wider_war",
        "regional":     "wider_war",
        "markets":      "markets",
        "economy":      "markets",
        "oil":          "markets",
        "energy":       "markets",
        "india":        "india",
        "india_impact": "india",
    }
    return mapping.get(t, "war")


def _build_india_impact(report: dict) -> list:
    return [{
        "headline":    i.get("headline", ""),
        "detail":      i.get("detail", ""),
        "category":    i.get("category", ""),
        "significance":i.get("significance", "MEDIUM"),
        "full_detail": i.get("full_detail", ""),
        "sourceUrl":   i.get("sourceUrl", "#"),
        "source":      i.get("source", "Source"),
    } for i in report.get("india_impact", [])]


def build_dashboard():
    REPORTS_DIR.mkdir(exist_ok=True)

    # Load up to 48 most recent reports
    reports = []
    for f in sorted(REPORTS_DIR.glob("*.json"), reverse=True)[:48]:
        try:
            reports.append(json.loads(f.read_text()))
        except Exception:
            pass

    latest = reports[0] if reports else {}
    level  = latest.get("escalation_level", "CRITICAL")

    # ── Alerts (typewriter headlines) ─────────────────────────────────────────
    alerts = []
    for dev in latest.get("key_developments", [])[:6]:
        headline = dev.get("headline", "")
        detail   = (dev.get("detail", ""))[:80]
        actor    = dev.get("actor", "")
        if headline:
            snippet = f"{detail}…" if len(dev.get("detail","")) > 80 else detail
            alerts.append(f"{actor}: {headline} · {snippet}" if actor else headline)
    if not alerts:
        alerts = [latest.get("executive_summary", "Monitoring live feeds...")]

    # ── Hero stats ────────────────────────────────────────────────────────────
    updates_today = sum(
        1 for r in reports
        if r.get("generated_at", "").startswith(
            datetime.now(timezone.utc).strftime("%Y-%m-%d")
        )
    )
    hero_stats = {
        "tension":      level,
        "updatesToday": updates_today or len(reports),
        "lastUpdated":  latest.get("generated_at", ""),
        "sourcesUsed":  latest.get("sources_used", 0),
    }

    # ── Tension meters ────────────────────────────────────────────────────────
    tone = latest.get("sentiment", {}).get("overall_tone", "")
    tone_boost = {"VOLATILE":8,"ESCALATING":5,"TENSE":2,"STABLE":-10,"DE-ESCALATING":-15}.get(tone, 0)
    base = _level_to_pct(level)
    tension_meters = [
        {"label":"US vs Iran",        "pct":min(98, base+tone_boost),    "lvl":level,      "color":_level_color(level)},
        {"label":"Israel vs Iran",    "pct":min(98, base+tone_boost-8),  "lvl":level,      "color":_level_color(level)},
        {"label":"Gaza ceasefire",    "pct":max(10, 100-base+5),          "lvl":"Holding",  "color":"var(--green)"},
        {"label":"Nuclear progress",  "pct":min(98, base-5+tone_boost),  "lvl":"High",     "color":"var(--amber)"},
        {"label":"Regional war risk", "pct":min(95, base-10+tone_boost), "lvl":"Elevated", "color":"var(--red)"},
    ]

    # ── News cards — include type so Daily Digest categories work ─────────────
    news_cards = []
    for dev in latest.get("key_developments", []):
        raw_type = dev.get("type", "war")
        norm_type = _normalise_type(raw_type)

        news_cards.append({
            "badgeClass":   _sig_badge(dev.get("significance", "MEDIUM")),
            "badgeLabel":   dev.get("significance", "Medium").capitalize(),
            "actorClass":   _actor_class(dev.get("actor", "Other")),
            "actor":        dev.get("actor", "Other"),
            "time":         _time_ago(latest.get("generated_at", "")),
            "headline":     dev.get("headline", ""),
            "summary":      dev.get("detail", ""),
            "whyTxt":       latest.get("escalation_reason", ""),
            "orgs":         [dev.get("actor", "Other")],
            "fullAnalysis": dev.get("fullAnalysis", ""),
            "sourceUrl":    dev.get("sourceUrl", "#"),
            "sourceLabel":  dev.get("sourceLabel", dev.get("source", "Source")),
            # CRITICAL: type field so index.html Daily Digest can categorise
            "type":         norm_type,
        })

    # Add "what to watch" card
    if latest.get("what_to_watch_next"):
        news_cards.append({
            "badgeClass":"b-gray","badgeLabel":"Analysis","actorClass":"p-gray",
            "actor":"Monitor","time":_time_ago(latest.get("generated_at","")),
            "headline":"What to watch in the next 6 hours",
            "summary":latest.get("what_to_watch_next",""),
            "whyTxt":latest.get("executive_summary",""),
            "orgs":[],"fullAnalysis":"","sourceUrl":"#","sourceLabel":"WarWatch",
            "type":"war",
        })

    # ── History for escalation chart ──────────────────────────────────────────
    history = [
        {
            "t":    r.get("generated_at", ""),
            "l":    r.get("escalation_level", "MEDIUM"),
            "tone": r.get("sentiment", {}).get("overall_tone", ""),
        }
        for r in reversed(reports[:20])
    ]

    # ── Full payload ──────────────────────────────────────────────────────────
    payload = {
        "generatedAt":     latest.get("generated_at", ""),
        "escalationLevel": level,
        "alerts":          alerts,
        "heroStats":       hero_stats,
        "tensionMeters":   tension_meters,
        "newsCards":       news_cards,
        "sentiment":       latest.get("sentiment", {}),
        "terms":           latest.get("terminology_explained", []),
        "history":         history,
        "execSummary":     latest.get("executive_summary", ""),
        "totalReports":    len(reports),
        "execSummaryRich": latest.get("execSummaryRich", latest.get("executive_summary", "")),
        "indiaSummary":    latest.get("indiaSummary", latest.get("india_summary", "")),
        "indiaImpact":     _build_india_impact(latest),
        "indiaMeter":      latest.get("indiaMeter", {"pct":72,"lvl":"High","color":"#d4892a"}),
    }

    js = f"window.WARWATCH_LIVE = {json.dumps(payload, indent=2)};\n"
    Path("live_data.js").write_text(js, encoding="utf-8")
    print(f"[OK] live_data.js written — {len(news_cards)} cards, level={level}")


if __name__ == "__main__":
    build_dashboard()
